# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

# MyBatis-Plus开发环境配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: ""

logging:
  level:
    com.cjy: debug
    org.springframework: info
    org.mybatis: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
