spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
# 热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
      poll-interval: 2000ms      # 每2秒检查一次变化
      quiet-period: 1000ms      # 等待1秒后再重启
# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8090






